import { KiaSeltos1 } from "../assets/Images";

let sliderData;
export default  sliderData=[
    {
      id:1,
      image:KiaSeltos1,
      name:"Kia Seltos",
      price:"10.90 - 20.45 Lakh",
      rating:"4.5",
      reviewCount:"500",
      transmission:"Automatic/Mannual",
      engine:"1482 cc - 1497 cc",
      fuelType:"Petrol",
      mileage:"17 - 20.7 kmpl",
      power:"113.42 - 157.81 bhp",
      bootSpace:"433 Litres	",
      airbag:"6",
      currentlyViewing:"Currently Viewing	",
    },
    {
      id:2,
      image:KiaSeltos1,
      name:"Kia Seltos",
      price:"10.90 - 20.45 Lakh",
      rating:"4.5",
      reviewCount:"500",
      transmission:"Automatic/Mannual",
      engine:"1482 cc - 1497 cc",
      fuelType:"Petrol",
      mileage:"17 - 20.7 kmpl",
      power:"113.42 - 157.81 bhp",
      bootSpace:"433 Litres	",
      airbag:"6",
      currentlyViewing:"Currently Viewing	",
    },
    {
      id:3,
      image:KiaSeltos1,
      name:"Kia Seltos",
      price:"10.90 - 20.45 Lakh",
      rating:"4.5",
      reviewCount:"500",
      transmission:"Automatic/Mannual",
      engine:"1482 cc - 1497 cc",
      fuelType:"Petrol",
      mileage:"17 - 20.7 kmpl",
      power:"113.42 - 157.81 bhp",
      bootSpace:"433 Litres	",
      airbag:"6",
      currentlyViewing:"Currently Viewing	",
    },
    {
      id:4,
      image:KiaSeltos1,
      name:"Kia Seltos",
      price:"10.90 - 20.45 Lakh",
      rating:"4.5",
      reviewCount:"500",
      transmission:"Automatic/Mannual",
      engine:"1482 cc - 1497 cc",
      fuelType:"Petrol",
      mileage:"17 - 20.7 kmpl",
      power:"113.42 - 157.81 bhp",
      bootSpace:"433 Litres	",
      airbag:"6",
      currentlyViewing:"Currently Viewing	",
    },
    {
      id:5,
      image:KiaSeltos1,
      name:"Kia Seltos",
      price:"10.90 - 20.45 Lakh",
      rating:"4.5",
      reviewCount:"500",
      transmission:"Automatic/Mannual",
      engine:"1482 cc - 1497 cc",
      fuelType:"Petrol",
      mileage:"17 - 20.7 kmpl",
      power:"113.42 - 157.81 bhp",
      bootSpace:"433 Litres	",
      airbag:"6",
      currentlyViewing:"Currently Viewing	",
    },
    {
      id:6,
      image:KiaSeltos1,
      name:"Kia Seltos",
      price:"10.90 - 20.45 Lakh",
      rating:"4.5",
      reviewCount:"500",
      transmission:"Automatic/Mannual",
      engine:"1482 cc - 1497 cc",
      fuelType:"Petrol",
      mileage:"17 - 20.7 kmpl",
      power:"113.42 - 157.81 bhp",
      bootSpace:"433 Litres	",
      airbag:"6",
      currentlyViewing:"Currently Viewing	",
    },
    {
        id:7,
        image:KiaSeltos1,
        name:"Kia Seltos",
        price:"10.90 - 20.45 Lakh",
        rating:"4.5",
        reviewCount:"500",
        transmission:"Automatic/Mannual",
        engine:"1482 cc - 1497 cc",
        fuelType:"Petrol",
        mileage:"17 - 20.7 kmpl",
        power:"113.42 - 157.81 bhp",
        bootSpace:"433 Litres	",
        airbag:"6",
        currentlyViewing:"Currently Viewing	",
      },
      {
        id:8,
        image:KiaSeltos1,
        name:"Kia Seltos",
        price:"10.90 - 20.45 Lakh",
        rating:"4.5",
        reviewCount:"500",
        transmission:"Automatic/Mannual",
        engine:"1482 cc - 1497 cc",
        fuelType:"Petrol",
        mileage:"17 - 20.7 kmpl",
        power:"113.42 - 157.81 bhp",
        bootSpace:"433 Litres	",
        airbag:"6",
        currentlyViewing:"Currently Viewing	",
      },
  ];