export {default as Dashboard} from './Dashboard/Dashboard';
export {default as Inventory} from './Inventory/Inventory';
export {default as MasterInventory} from './Inventory/MasterInventory';
export {default as Leads}     from './Leads/Leads';
export {default as MarketAnalytics} from './MarketAnalytics/MarketAnalytics';
export {default as FinancePartners} from './FinancePartners/FinancePartners'
export {default as InsurancePartners} from './InsurancePartners/InsurancePartners'
export {default as BBNDInventory} from './Inventory/BBNDInventory';
export {default as Customers} from './Customers/Customer';
export {default as ContactUs} from './ContactUs/ContactUs';
export {default as Settings} from './Settings/Settings';
export {default as Strategytools} from './StrategyTools/Strategytools'
export {default as Datasync} from './DataSync/Datasync';
export {default as OldDataLeads} from './Leads/OldDataLeads';